### ISSUE TITLE
Issue within import with batches, unexpected status code: 502

### ISSUE THREAD

**Issue by zakaria47fs** [semi-technologies/weaviate-python-client#161]
I am using WCS, 
Sometimes I randomly get this error:
`weaviate.exceptions.UnexpectedStatusCodeException: Create objects in batch! Unexpected status code: 502, with response body: None`
When I retry the same script sometime it goes smoothly! Cannot find for what reason! This is the batch config I m using:
`client.batch.configure(
  batch_size=100, 
  dynamic=True,
  timeout_retries=3,
  callback=weaviate.util.check_batch_result,
  num_workers=3,
)`

Full error traceback:
`Traceback (most recent call last):
  File "run_migration.py", line 74, in <module>
    client.batch = experience_batch_push(client.batch, profile.get('experience', []), uuid_profile)
  File "/home/ubuntu/profiles-search/profiles-search-platform/weaviate_migration/migrate_utils.py", line 78, in experience_batch_push
    batch.add_data_object(
  File "/home/ubuntu/profiles-search/env_profiles_search/lib/python3.8/site-packages/weaviate/batch/crud_batch.py", line 420, in add_data_object
    self._auto_create()
  File "/home/ubuntu/profiles-search/env_profiles_search/lib/python3.8/site-packages/weaviate/batch/crud_batch.py", line 1023, in _auto_create
    self._send_batch_requests(force_wait=False)
  File "/home/ubuntu/profiles-search/env_profiles_search/lib/python3.8/site-packages/weaviate/batch/crud_batch.py", line 949, in _send_batch_requests
    response_objects, nr_objects = done_future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/profiles-search/env_profiles_search/lib/python3.8/site-packages/weaviate/batch/crud_batch.py", line 895, in _flush_in_thread
    response = self._create_data(
  File "/home/ubuntu/profiles-search/env_profiles_search/lib/python3.8/site-packages/weaviate/batch/crud_batch.py", line 566, in _create_data
    raise UnexpectedStatusCodeException(f"Create {data_type} in batch", response)
weaviate.exceptions.UnexpectedStatusCodeException: Create objects in batch! Unexpected status code: 502, with response body: None
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.31.21.65', 39812), raddr=('34.238.27.150', 9702)>`

**Comment by dirkkul** [comment]
Hi @zakaria47fs, 502 is Bad Gateway. Maybe someone from the WCS team know more about this? @Glockenbeat maybe?
