### ISSUE TITLE
Missing cardinality key gives error even if the field is not needed

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-python-client#24]
The client gives an error if the "cardinality" field isn't set on all fields. However, the cardinality field only has to be set for references.

```
Traceback (most recent call last):
  File "./import.py", line 12, in <module>
    CLIENT.create_schema('schema.json')
  File "/usr/local/lib/python3.7/site-packages/weaviate/client.py", line 444, in create_schema
    loaded_schema[SCHEMA_CLASS_TYPE_THINGS]["classes"])
  File "/usr/local/lib/python3.7/site-packages/weaviate/client.py", line 484, in _create_class_with_primitives
    schema_class["properties"] = self._get_primitive_properties(weaviate_class["properties"])
  File "/usr/local/lib/python3.7/site-packages/weaviate/client.py", line 514, in _get_primitive_properties
    "cardinality": property_["cardinality"],
KeyError: 'cardinality'
```

**Comment by fefi42** [comment]
Fixed in realease `0.4.0`
