### ISSUE TITLE
The check whether classification is still running sometimes throws an exception. See the message below

### ISSUE THREAD

**Issue by michaverhagen** [semi-technologies/weaviate-python-client#43]
{'basedOnProperties': ['shortDescription'], 'class': 'Product', 'classifyProperties': ['ofFlavour'], 'id': 'e4ad5c2e-3e3e-470f-b942-93df9cd26d0e', 'k': 7, 'meta': {'completed': '0001-01-01T00:00:00.000Z', 'started': '2020-12-11T08:41:16.188Z'}, 'status': 'running', 'type': 'knn'}
Classifying  All.Traceback (most recent call last):
  File "./validate.py", line 28, in <module>
    main()
  File "./validate.py", line 19, in main
    validateClassification(config, data)
  File "PATH/modules/API.py", line 96, in validateClassification
    executeClassification(client, config)
  File "PATH/modules/ClassifyData.py", line 83, in executeClassification
    print_classification_status(client, status, "All")
  File "PATH/modules/ClassifyData.py", line 16, in print_classification_status
    while client.classification.is_running(status['id']):
  File "PATH/Envs/env1/lib/python3.8/site-packages/weaviate/classification/classify.py", line 67, in is_running
    return self._check_status(classification_uuid, "running")
  File "PATH/Envs/env1/lib/python3.8/site-packages/weaviate/classification/classify.py", line 71, in _check_status
    response = self.get(classification_uuid)
  File "PATH/Envs/env1/lib/python3.8/site-packages/weaviate/classification/classify.py", line 45, in get
    raise UnexpectedStatusCodeException("Get classification status", response)
weaviate.exceptions.UnexpectedStatusCodeException: Unexpected status code: 502, with response body: None

**Comment by StefanBogdan** [comment]
This error does not happen anymore. I am closing it. If anyone encounters it, please re-open this issue.
